routes/web.php
Route::get('/imports', 'ImportController@indexAction')->name('imports')->middleware('can:imports');
Route::get('/import_orders', 'ImportController@ordersImport')->name('import.orders')->middleware('can:import.orders');
Route::post('/import_orders_parse', 'ImportController@parseOrdersImport')->name('import.orders.parse')->middleware('can:import.orders.parse');
Route::post('/import_order_shipments_parse', 'ImportController@parseOrderShipmentsImport')->name('import.order_shipments.parse')->middleware('can:import.order_shipments.parse');

Route::get('/import_listings', 'ImportController@listingsImport')->name('import.listings')->middleware('can:import.listings');
Route::post('/import_listings_parse', 'ImportController@parseListingsImport')->name('import.listings.parse')->middleware('can:import.listings.parse');

Route::get('/import_inventory', 'ImportController@inventoryImport')->name('import.inventory')->middleware('can:import.inventory');
Route::post('/import_inventory_parse', 'ImportController@parseInventoryImport')->name('import.inventory.parse')->middleware('can:import.inventory.parse');

Route::get('/import_finances', 'ImportController@financesImport')->name('import.finances')->middleware('can:import.finances');
Route::post('/import_finances_parse', 'ImportController@parseFinancesImport')->name('import.finances.parse')->middleware('can:import.finances.parse');

Route::get('/import_ads', 'ImportController@adsImport')->name('import.ads')->middleware('can:import.ads');
Route::post('/import_ads_parse', 'ImportController@parseAdsImport')->name('import.ads.parse')->middleware('can:import.ads.parse');

Route::get('/import_campaigns', 'ImportController@campaignsImport')->name('import.campaigns')->middleware('can:import.campaigns');
Route::post('/import_campaigns_parse', 'ImportController@parseCampaignsImport')->name('import.campaigns.parse')->middleware('can:import.campaigns.parse');
Route::post('/import_searchterms_parse', 'ImportController@parseSearchTermsImport')->name('import.searchterms.parse')->middleware('can:import.searchterms.parse');

Route::get('/import_business', 'ImportController@businessImport')->name('import.business')->middleware('can:import.business');
Route::post('/import_business_parse', 'ImportController@parseBusinessImport')->name('import.business.parse')->middleware('can:import.business.parse');

Route::get('/import_stats', 'ImportController@ImportStats')->name('import.stats')->middleware('can:import.stats');
Route::any('/fetchImportStatsRows', 'ImportController@fetchImportStatsRowsAction')->name('import.fetchimportstatsrows')->middleware('can:import.fetchimportstatsrows');

Route::get('/marketing/order-list', 'MarketingController@listOrders')->name('marketing.listOrders')->middleware('can:marketing.listOrders');
Route::get('/marketing/order-shipment-list', 'MarketingController@listOrderShipments')->name('marketing.listOrderShipments')->middleware('can:marketing.listOrderShipments');
Route::post('/marketing/updateReviewStatus', 'MarketingController@updateReviewStatus')->name('marketing.updateReviewStatus')->middleware('can:marketing.updateReviewStatus');
Route::post('/marketing/updateCustomerInfo', 'MarketingController@updateCustomerInfo')->name('marketing.updateCustomerInfo')->middleware('can:marketing.updateCustomerInfo');

Route::get('/gift-card-template/asin/{asin}', 'GiftCardTemplateController@get')->name('gift-card-template.get')->middleware('can:gift-card-template.get');

Route::get('/managed-review-order/own-orders', 'ManagedReviewOrderController@ownOrders')->name('managed-review-order.own-orders')->middleware('can:managed-review-order.own-orders');
Route::get('/managed-review-order/check-review-orders', 'ManagedReviewOrderController@checkReviewOrders')->name('managed-review-order.check-review-orders')->middleware('can:managed-review-order.check-review-orders');
Route::get('/managed-review-order/need-review-orders', 'ManagedReviewOrderController@needReviewOrders')->name('managed-review-order.need-review-orders')->middleware('can:managed-review-order.need-review-orders');

Route::get('/customers/dashboard', 'CustomerController@dashboard')->name('customers.dashboard')->middleware('can:customers.dashboard');
Route::get('/customers/all/{country?}', 'CustomerController@all')->name('customers.all')->middleware('can:customers.all');
Route::get('/customers/repeat-buyers/{country?}', 'CustomerController@repeatBuyers')->name('customers.repeat-buyers')->middleware('can:customers.repeat-buyers');
Route::get('/customers/real-email-buyers/{country?}', 'CustomerController@realEmailBuyers')->name('customers.real-email-buyers')->middleware('can:customers.real-email-buyers');
Route::get('/customers/positive-reviewer/{country?}', 'CustomerController@positiveReviewer')->name('customers.positive-reviewer')->middleware('can:customers.positive-reviewer');
Route::get('/customers/negative-reviewer/{country?}', 'CustomerController@negativeReviewer')->name('customers.negative-reviewer')->middleware('can:customers.negative-reviewer');
Route::get('/customers/{country}/dashboard', 'CustomerController@countryDashboard')->name('customers.country-dashboard')->middleware('can:customers.country-dashboard');
Route::get('/customers/{id}', 'CustomerController@show')->name('customers.show')->middleware('can:customers.show');
Route::get('/customers/export/form', 'CustomerController@exportForm')->name('customers.export-form')->middleware('can:customers.export-form');
Route::post('/customers/export/generate', 'CustomerController@exportGenerate')->name('customers.export-generate')->middleware('can:customers.export-generate');
Route::get('/customers/export/history', 'CustomerController@exportHistory')->name('customers-export-history')->middleware('can:customers-export-history');

//!ATTENTION: Don't use Route::resources([]), it may break other parts. see AuthServiceProvider@getRoutes

Route::get('/claim-review-campaign/products/overview', 'ClaimReviewCampaignController@productsCampaignOverview')->name('claim-review-campaign.products-overview');
Route::get('/claim-review-campaign/update-product-statistic', 'ClaimReviewCampaignController@updateProductStatistic')->name('claim-review-campaign.update-product-statistic');
Route::get('/claim-review-campaign/filter-shipments', 'ClaimReviewCampaignController@filterShipments')->name('claim-review-campaign.filter-shipments')->middleware('can:claim-review-campaign.filter-shipments');
Route::post('/claim-review-campaign/filter-shipments', 'ClaimReviewCampaignController@filterShipments')->name('claim-review-campaign.filter-shipments')->middleware('can:claim-review-campaign.filter-shipments');
Route::get('/download/{file}', 'DownloadController@download')->name('download-file');

Route::resource('claim-review-campaign', 'ClaimReviewCampaignController');

Route::resource('gift-card-template', 'GiftCardTemplateController');
Route::resource('leave-review-task', 'LeaveReviewTaskController');
Route::resource('managed-review-order', 'ManagedReviewOrderController');
Route::resource('owned-buyer-cart-item', 'OwnedBuyerCartItemController');
Route::resource('divvy-transaction-record', 'DivvyTransactionRecordController');
Route::resource('clicksend-history', 'ClickSendHistoryController');

Route::resource('customers', 'CustomerController', ['except' => ['show']]);

Route::resource('customers.customer-notes', 'CustomerNoteController');

Route::resource('owned-buyer', 'OwnedBuyerController', ['except' => ['show']]);
Route::get('/owned-buyer/{id}', 'OwnedBuyerController@show')->name('owned-buyer.show');

Route::resource('product-cost', 'ProductCostController', ['only' => ['store', 'update', 'destroy']]);
Route::resource('product-shipping-cost', 'ProductShippingCostController', ['only' => ['store', 'update', 'destroy']]);
Route::resource('product-fbm-shipping-cost', 'ProductFbmShippingCostController', ['only' => ['store', 'update', 'destroy']]);


Route::post('/claim-review-campaign/{id}/ajaxUpdate', 'ClaimReviewCampaignController@ajaxUpdate')->name('claim-review-campaign.ajaxUpdate')->middleware('can:claim-review-campaign.ajaxUpdate');
Route::put('/claim-review-campaign/{id}/send', 'ClaimReviewCampaignController@send')->name('claim-review-campaign.send')->middleware('can:claim-review-campaign.send');
Route::post('/claim-review-campaign/{id}/clicksendConfig', 'ClaimReviewCampaignController@createClicksendConfig')->name('claim-review-campaign.createClicksendConfig')->middleware('can:claim-review-campaign.createClicksendConfig');
Route::post('/claim-review-campaign/{id}/config', 'ClaimReviewCampaignController@createConfig')->name('claim-review-campaign.createConfig')->middleware('can:claim-review-campaign.createConfig');
Route::get('/claim-review-campaign/{id}/review-clicksend', 'ClaimReviewCampaignController@clicksendReview')->name('claim-review-campaign.review-clicksend')->middleware('can:claim-review-campaign.review-clicksend');
Route::get('/claim-review-campaign/{id}/review', 'ClaimReviewCampaignController@clicksendReview')->name('claim-review-campaign.review')->middleware('can:claim-review-campaign.review');
Route::put('/claim-review-campaign/{id}/send-via-api', 'ClaimReviewCampaignController@sendViaApi')->name('claim-review-campaign.send-via-api')->middleware('can:claim-review-campaign.send-via-api');

Route::post('/owned_buyer/import', 'OwnedBuyerController@import')->name('owned_buyer.import')->middleware('can:owned_buyer.import');
Route::get('/owned_buyer/find-eligible-buyers/{asin?}', 'OwnedBuyerController@findEligibleBuyers')->name('owned_buyer.find-eligible-buyers')->middleware('can:owned_buyer.find-eligible-buyers');
Route::get('/owned_buyer/find-eligible-buyers/{asin}/last-order-before/{lastOrderBefore}/last-review-before/{lastReviewBefore}/reviewRateLessThan/{reviewRateLessThan}', 'OwnedBuyerController@findEligibleBuyers')->name('owned_buyer.find-eligible-buyers-with-parameters')->middleware('can:owned_buyer.find-eligible-buyers-with-parameters');

app/Http/Controllers/GiftCardTemplateController.php
<?php

namespace App\Http\Controllers;

use App\GiftCardTemplate;
use Illuminate\Http\Request;
use App\Grids\GiftCardTemplateGrid;

class GiftCardTemplateController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        $grid = (new GiftCardTemplateGrid())->generateGrid();
        return view('gift-card-template.index', ['grid' => $grid]);
    }

    public function get(Request $request)
    {
        $asin = $request->asin;
        $templates = GiftCardTemplate::where('asin', $asin)->get();
        return response()->json($templates);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $channels = config('claimreview.channels');
        return view('gift-card-template.create', ['channels' => $channels]);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $gcTemplate = $this->save($request);
        return redirect()->route('gift-card-template.show', ['giftCardTemplate' => $gcTemplate]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\GiftCardTemplate  $giftCardTemplate
     * @return \Illuminate\Http\Response
     */
    public function show(GiftCardTemplate $giftCardTemplate)
    {
        return view('gift-card-template.show', ["giftCardTemplate" => $giftCardTemplate]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\GiftCardTemplate  $giftCardTemplate
     * @return \Illuminate\Http\Response
     */
    public function edit(GiftCardTemplate $giftCardTemplate)
    {
        $channels = config('claimreview.channels');
        return view('gift-card-template.edit', ["giftCardTemplate"=>$giftCardTemplate, "channels"=>$channels]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\GiftCardTemplate  $giftCardTemplate
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, GiftCardTemplate $giftCardTemplate)
    {   
        $gcTemplate = $this->save($request, $giftCardTemplate);
        return redirect()->route('gift-card-template.show', ['giftCardTemplate' => $gcTemplate]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\GiftCardTemplate  $giftCardTemplate
     * @return \Illuminate\Http\Response
     */
    public function destroy(GiftCardTemplate $giftCardTemplate)
    {
        $giftCardTemplate->delete();
        return response("DELETED", 200);
    }

    private function save(Request $request, GiftCardTemplate $giftCardTemplate = null) {
        if (!$giftCardTemplate) {
            $giftCardTemplate = new GiftCardTemplate();
            $giftCardTemplate->created_by = auth()->user()->id;
        }
        $giftCardTemplate->name = $request->input("name");
        $giftCardTemplate->asin = $request->input("asin");
        $giftCardTemplate->amount = $request->input("amount");
        $giftCardTemplate->channel = $request->input("channel");
        $giftCardTemplate->channel_detail = $request->input("channel_detail");
        $giftCardTemplate->version = $request->input("version");
        $giftCardTemplate->template_type = $request->input("template_type");
        $giftCardTemplate->note = $request->input("note");
        if ($request->file('front-design-file')) {
            $fronDesignPath = $request->file('front-design-file')->store('gift-card-template', config('giftcard.storage'));
            $giftCardTemplate->front_design = $fronDesignPath;
        }
        if ($request->file('back-design-file')) {
            $backDesignPath = $request->file('back-design-file')->store('gift-card-template', config('giftcard.storage'));
            $giftCardTemplate->back_design = $backDesignPath;
        }
        
        if ($request->file('attachment1-file')) {
            $attachment1Path = $request->file('attachment1-file')->store('gift-card-template', config('giftcard.storage'));
            $giftCardTemplate->attachment1 = $attachment1Path;
        }
        if ($request->file('attachment2-file')) {
            $attachment2Path = $request->file('attachment2-file')->store('gift-card-template', config('giftcard.storage'));
            $giftCardTemplate->attachment2 = $attachment2Path;
        }
        $giftCardTemplate->save();
        return $giftCardTemplate;
    }
}

resources/views/gift-card-template/create.blade.php
@extends('layouts.master')
@section('title', "New Gift Card Template")
@section('content')
<ol class="breadcrumb">
  <li><a href="{{route('gift-card-template.index')}}">Gift Card Templates List</a></li>
  <li class="active">Create</li>
</ol>
<div class="row">
	 <div class="col-md-6 mx-auto col-md-offset-3">
    {{ Form::open(array('url' => route('gift-card-template.store'),'files'=>'true')) }}
      {{Form::token()}}
      <div class="form-group">
        <label for="name">Name: <strong class="text-danger">*</strong></label>
        <input required type="text" name="name" class="form-control" id="name">
      </div>
      <div class="form-group">
        <label for="asin">ASIN: <strong class="text-danger">*</strong></label>
        <input required type="text" name="asin" class="form-control" id="asin">
      </div>
      <div class="form-group">
        <label for="amount">Gift Card Amount: <strong class="text-danger">*</strong> </label>
        <input required type="number" name="amount" class="form-control" id="amount">
      </div>
      <div class="form-group">
        <label for="channel">Channel *:</label>
        <select required name="channel" id="channel" class="form-control">
          <option value="">--select--</option>
          <?php
          foreach ($channels as $val => $text)
            if ($val == "thank2u.com") {
              echo('<option selected="selected" value='.$val.'>'.$text.'</option>');
            } else {
              echo('<option value='.$val.'>'.$text.'</option>');
            }
          ?>
        </select>
      </div>
      <div class="form-group">
        <label for="channel_detail">Channel Detail: <strong class="text-danger">*</strong> </label>
        <input required type="text" name="channel_detail" class="form-control" id="channel_detail">
      </div>
      <div class="form-group">
        <label for="version">Version: <strong class="text-danger">*</strong> </label>
        <input required type="text" name="version" class="form-control" id="version">
      </div>
      <div class="form-group">
        <label for="template_type"> Type: <strong class="text-danger">*</strong> </label>
        <select required class="form-control"  name="template_type" id="template_type">
          @foreach(App\GiftCardTemplate::$templateTypes as $value=>$text)
            <option value="{{$value}}">{{$text}}</option>
          @endforeach
        </select>
      </div>
      <div class="form-group">
        <label for="">
          Front Design Image: <span class="fa fa-info-circle" tabindex="0" role="button" data-toggle="popover" data-element="#design-image-hint" data-trigger="focus" data-placement="top" data-original-title="" title=""></span>
        </label>
        <img class="preview-image thumbnail" src="/images/noImageUploaded.png" alt="Front Design" />
        <input class="previe-image-upload" type="file" name="front-design-file" class="form-control" id="front-design" accept="image/*,.pdf">
        <p id="design-image-hint" class="hidden">The image uploaded here will show on list page and campaign's select options for better recognization</p>
      </div>
      <div class="form-group">
        <label for="">Back Design Image: <span class="fa fa-info-circle" tabindex="0" role="button" data-toggle="popover" data-element="#design-image-hint" data-trigger="focus" data-placement="top" data-original-title="" title=""></span>
        </label>
        <img class="preview-image thumbnail" src="/images/noImageUploaded.png" alt="Back Design" />
        <input class="previe-image-upload" type="file" name="back-design-file" class="form-control" id="back-design" accept="image/*,.pdf">
      </div>
      <div class="form-group">
        <label for="attachment1">attachment 1 </label>
        <input type="file" name="attachment1-file" class="form-control" id="attachment1" accept="image/*,.pdf">
      </div>
      <div class="form-group">
        <label for="attachment2">attachment 2 </label>
        <input type="file" name="attachment2-file" class="form-control" id="attachment2" accept="image/*,.pdf">
      </div>
      <div class="form-group">
        <label for="note">Note:</label>
        <textarea class="form-control" rows="10" name="note" id="note"></textarea>
      </div>
      <div class="form-group">
        <button type="submit" class="btn btn-primary btn-lg btn-submit">Submit</button>
      </div>
    {{ Form::close() }}
  </div>
</div>
<script>
$(document).ready(function() {

  $('[data-toggle="popover"]').popover({
    content:function(){
      var elmt = $(this).attr('data-element')
      return $(elmt).html()

    }
  })

  $("input.previe-image-upload").change(function() {
    readURL(this);
  });
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();
      
      reader.onload = function(e) {
        $(input).siblings('img.preview-image').attr('src', e.target.result);
      }
      
      reader.readAsDataURL(input.files[0]);
    }
  }

})

</script>
@endsection

resources/views/gift-card-template/edit.blade.php
@extends('layouts.master')
@section('title', "Edit Gift Card Template: " . $giftCardTemplate->name)
@section('content')
<ol class="breadcrumb">
  <li><a href="{{route('gift-card-template.index')}}">Gift Card Templates List</a></li>
  <li><a href="{{route('gift-card-template.show', ['giftCardTemplate' => $giftCardTemplate])}}">{{$giftCardTemplate->name}}</a></li>
  <li class="active">Edit</li>
</ol>

<div class="row">
	 <div class="col-md-6 mx-auto col-md-offset-3">
    {{ Form::open(array('url' => route('gift-card-template.update', ['giftCardTemplate' => $giftCardTemplate]),'files'=>'true', 'method'=>'put')) }}
      <div class="form-group">
        <label for="name">Name: <strong class="text-danger">*</strong></label>
        <input required type="text" name="name" class="form-control" id="name" value="{{$giftCardTemplate->name}}">
      </div>
      <div class="form-group">
        <label for="asin">ASIN: <strong class="text-danger">*</strong></label>
        <input required type="text" name="asin" class="form-control" id="asin" value="{{$giftCardTemplate->asin}}">
      </div>
      <div class="form-group">
        <label for="amount">Gift Card Amount: <strong class="text-danger">*</strong> </label>
        <input required type="number" name="amount" class="form-control" id="amount" value="{{$giftCardTemplate->amount}}">
      </div>
      <div class="form-group">
        <label for="channel">Channel *:</label>
        <select required name="channel" id="channel" class="form-control">
          <option value="">--select--</option>
          <?php
          foreach ($channels as $val => $text)
            if ($val == "website") {
              echo('<option selected="selected" value='.$val.'>'.$text.'</option>');
            } else {
              echo('<option value='.$val.'>'.$text.'</option>');
            }
          ?>
        </select>
      </div>
      <div class="form-group">
        <label for="channel_detail">Channel Detail: <strong class="text-danger">*</strong> </label>
        <input required type="text" name="channel_detail" class="form-control" id="channel_detail" value="{{$giftCardTemplate->channel_detail}}">
      </div>
      <div class="form-group">
        <label for="version">Version: <strong class="text-danger">*</strong> </label>
        <input required type="text" name="version" class="form-control" id="version" value="{{$giftCardTemplate->version}}">
      </div>
      <div class="form-group">
        <label for="template_type"> Type: <strong class="text-danger">*</strong> </label>
        <select required class="form-control"  name="template_type" id="template_type">
          @foreach(App\GiftCardTemplate::$templateTypes as $value=>$text)
            <option value="{{$value}}" {{$giftCardTemplate->template_type ? "selected" :  ""}} >{{$text}}</option>
          @endforeach
        </select>
      </div>
      <div class="form-group">
        <label for="front-design">Front Design:  <strong class="text-danger">*</strong></label>
        <img class="preview-image thumbnail" src="{{$giftCardTemplate->getFrontDesignUrlAttribute()}}" alt="Front Design" />
        <input class="previe-image-upload" type="file" name="front-design-file" class="form-control" id="front-design" accept="image/*,.pdf">
      </div>
      <div class="form-group">
        <label for="back-design">Back Design:  <strong class="text-danger">*</strong></label>
        <img class="preview-image thumbnail" src="{{$giftCardTemplate->getBackDesignUrlAttribute()}}" alt="Back Design" />
        <input class="previe-image-upload" type="file" name="back-design-file" class="form-control" id="back-design" accept="image/*,.pdf">
      </div>
      <div class="form-group">
        <label for="attachment1">attachment 1 </label>
        @if ($giftCardTemplate->attachment1)
          <a target="_blank" href="{{$giftCardTemplate->attachment1Url}}">attachment 1</a>
        @endif
        <input type="file" name="attachment1-file" class="form-control" id="attachment1" accept="image/*,.pdf">
      </div>
      <div class="form-group">
        <label for="attachment2">attachment 2 </label>
        @if ($giftCardTemplate->attachment2)
          <a target="_blank" href="{{$giftCardTemplate->attachment2Url}}">attachment 2</a>
        @endif
        <input type="file" name="attachment2-file" class="form-control" id="attachment2" accept="image/*,.pdf">
      </div>
      <div class="form-group">
        <label for="note">Note:</label>
        <textarea class="form-control" rows="10" name="note" id="note">{{$giftCardTemplate->note}}</textarea>
      </div>
      <div class="form-group">
        <button type="submit" class="btn btn-primary btn-lg btn-submit">Update</button>
      </div>
    {{ Form::close() }}
  </div>
</div>
<script>
$(document).ready(function() {
  $("input.previe-image-upload").change(function() {
    readURL(this);
  });
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();
      
      reader.onload = function(e) {
        $(input).siblings('img.preview-image').attr('src', e.target.result);
      }
      
      reader.readAsDataURL(input.files[0]);
    }
  }

})

</script>
@endsection

resources/views/gift-card-template/index.blade.php
@extends('layouts.master')
@section('title', "Gift Card Templates")
@section('content')
<div class="btn-actions">
  <a href="{{route('gift-card-template.create')}}" class="btn btn-primary pull-right"><span class="" >Create New Gift Card Template</span></a>
</div>

{!! $grid !!}

<!-- Modal -->
<div class="modal fade" id="confirmDelete" role="dialog">
  <div class="modal-dialog">
  
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Are you sure you want to delete <b id="compaignName"></b>?</h4>
      </div>
      <div class="modal-body">
        <p class="text-default">Please input the ASIN below and then click delete if you really want to delete this campaign</p>
        <input type="text" id="confimName" class="form-control">
        <p id="wrong-name" class="text-danger">Your input is not exactly the same as the ASIN</p>
      </div>
      <div class="modal-footer">
        <i id="spinner" class="fa fa-circle-o-notch fa-spin" style="font-size:24px"></i>
        <div id="btn-group">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-danger" id="deleteBtn">Delete</button>
        </div>
      </div>
    </div>
    
  </div>
</div>
<script>

  $('#confirmDelete').on('show.bs.modal', function (event) {
    let button = $(event.relatedTarget);
    let id = button.data('id'); // Extract info from data-* attributes
    let name = button.data('name');
    let url = button.data('url');
    // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
    // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
    let modal = $(this);
    modal.find('#wrong-name').hide();
    modal.find('#btn-group').show();
    modal.find('#spinner').hide();
    modal.find('#compaignName').text(name);
    let input = modal.find('#confimName');
    $('#deleteBtn').on('click', function() {
      if (input.val().trim() == name.trim()) {
        modal.find('#wrong-name').hide();
        modal.find('#btn-group').hide();
        modal.find('#spinner').show();
        $.ajax({
          url: url,
          type: 'DELETE',
          success: function(res){
            console.log(res);
            button.closest('tr').remove();
            modal.modal('hide');
          },
          error: function(err) {
            modal.find('#btn-group').show();
            modal.find('#spinner').hide();
            console.log(err);
          }
        });
        
      } else {
        modal.find('#wrong-name').show();
      }
    })
  });

  $("#confirmDelete").on('hide.bs.modal' , function (event) {
    let modal = $(this);
    modal.find('#confimName').val("");
  })
</script>
@endsection