routes/web.php
Route::post('/redeems/{id}/send-invite-review-letter', 'RedeemController@sendInviteReviewLetter')->name('redeems.send-invite-review-letter')->middleware('can:redeems.send-invite-review-letter');
Route::get('/imports', 'ImportController@indexAction')->name('imports')->middleware('can:imports');
Route::get('/import_orders', 'ImportController@ordersImport')->name('import.orders')->middleware('can:import.orders');
Route::post('/import_orders_parse', 'ImportController@parseOrdersImport')->name('import.orders.parse')->middleware('can:import.orders.parse');
Route::post('/import_order_shipments_parse', 'ImportController@parseOrderShipmentsImport')->name('import.order_shipments.parse')->middleware('can:import.order_shipments.parse');

Route::get('/import_listings', 'ImportController@listingsImport')->name('import.listings')->middleware('can:import.listings');
Route::post('/import_listings_parse', 'ImportController@parseListingsImport')->name('import.listings.parse')->middleware('can:import.listings.parse');

Route::get('/import_inventory', 'ImportController@inventoryImport')->name('import.inventory')->middleware('can:import.inventory');
Route::post('/import_inventory_parse', 'ImportController@parseInventoryImport')->name('import.inventory.parse')->middleware('can:import.inventory.parse');

Route::get('/import_finances', 'ImportController@financesImport')->name('import.finances')->middleware('can:import.finances');
Route::post('/import_finances_parse', 'ImportController@parseFinancesImport')->name('import.finances.parse')->middleware('can:import.finances.parse');

Route::get('/import_ads', 'ImportController@adsImport')->name('import.ads')->middleware('can:import.ads');
Route::post('/import_ads_parse', 'ImportController@parseAdsImport')->name('import.ads.parse')->middleware('can:import.ads.parse');

Route::get('/import_campaigns', 'ImportController@campaignsImport')->name('import.campaigns')->middleware('can:import.campaigns');
Route::post('/import_campaigns_parse', 'ImportController@parseCampaignsImport')->name('import.campaigns.parse')->middleware('can:import.campaigns.parse');
Route::post('/import_searchterms_parse', 'ImportController@parseSearchTermsImport')->name('import.searchterms.parse')->middleware('can:import.searchterms.parse');

Route::get('/import_business', 'ImportController@businessImport')->name('import.business')->middleware('can:import.business');
Route::post('/import_business_parse', 'ImportController@parseBusinessImport')->name('import.business.parse')->middleware('can:import.business.parse');

Route::get('/import_stats', 'ImportController@ImportStats')->name('import.stats')->middleware('can:import.stats');
Route::any('/fetchImportStatsRows', 'ImportController@fetchImportStatsRowsAction')->name('import.fetchimportstatsrows')->middleware('can:import.fetchimportstatsrows');

Route::get('/marketing/order-list', 'MarketingController@listOrders')->name('marketing.listOrders')->middleware('can:marketing.listOrders');
Route::get('/marketing/order-shipment-list', 'MarketingController@listOrderShipments')->name('marketing.listOrderShipments')->middleware('can:marketing.listOrderShipments');
Route::post('/marketing/updateReviewStatus', 'MarketingController@updateReviewStatus')->name('marketing.updateReviewStatus')->middleware('can:marketing.updateReviewStatus');
Route::post('/marketing/updateCustomerInfo', 'MarketingController@updateCustomerInfo')->name('marketing.updateCustomerInfo')->middleware('can:marketing.updateCustomerInfo');

Route::get('/gift-card-template/asin/{asin}', 'GiftCardTemplateController@get')->name('gift-card-template.get')->middleware('can:gift-card-template.get');

Route::get('/managed-review-order/own-orders', 'ManagedReviewOrderController@ownOrders')->name('managed-review-order.own-orders')->middleware('can:managed-review-order.own-orders');
Route::get('/managed-review-order/check-review-orders', 'ManagedReviewOrderController@checkReviewOrders')->name('managed-review-order.check-review-orders')->middleware('can:managed-review-order.check-review-orders');
Route::get('/managed-review-order/need-review-orders', 'ManagedReviewOrderController@needReviewOrders')->name('managed-review-order.need-review-orders')->middleware('can:managed-review-order.need-review-orders');

Route::get('/customers/dashboard', 'CustomerController@dashboard')->name('customers.dashboard')->middleware('can:customers.dashboard');
Route::get('/customers/all/{country?}', 'CustomerController@all')->name('customers.all')->middleware('can:customers.all');
Route::get('/customers/repeat-buyers/{country?}', 'CustomerController@repeatBuyers')->name('customers.repeat-buyers')->middleware('can:customers.repeat-buyers');
Route::get('/customers/real-email-buyers/{country?}', 'CustomerController@realEmailBuyers')->name('customers.real-email-buyers')->middleware('can:customers.real-email-buyers');
Route::get('/customers/positive-reviewer/{country?}', 'CustomerController@positiveReviewer')->name('customers.positive-reviewer')->middleware('can:customers.positive-reviewer');
Route::get('/customers/negative-reviewer/{country?}', 'CustomerController@negativeReviewer')->name('customers.negative-reviewer')->middleware('can:customers.negative-reviewer');
Route::get('/customers/{country}/dashboard', 'CustomerController@countryDashboard')->name('customers.country-dashboard')->middleware('can:customers.country-dashboard');
Route::get('/customers/{id}', 'CustomerController@show')->name('customers.show')->middleware('can:customers.show');
Route::get('/customers/export/form', 'CustomerController@exportForm')->name('customers.export-form')->middleware('can:customers.export-form');
Route::post('/customers/export/generate', 'CustomerController@exportGenerate')->name('customers.export-generate')->middleware('can:customers.export-generate');
Route::get('/customers/export/history', 'CustomerController@exportHistory')->name('customers-export-history')->middleware('can:customers-export-history');

//!ATTENTION: Don't use Route::resources([]), it may break other parts. see AuthServiceProvider@getRoutes

Route::get('/claim-review-campaign/products/overview', 'ClaimReviewCampaignController@productsCampaignOverview')->name('claim-review-campaign.products-overview');
Route::get('/claim-review-campaign/update-product-statistic', 'ClaimReviewCampaignController@updateProductStatistic')->name('claim-review-campaign.update-product-statistic');
Route::get('/claim-review-campaign/filter-shipments', 'ClaimReviewCampaignController@filterShipments')->name('claim-review-campaign.filter-shipments')->middleware('can:claim-review-campaign.filter-shipments');
Route::post('/claim-review-campaign/filter-shipments', 'ClaimReviewCampaignController@filterShipments')->name('claim-review-campaign.filter-shipments')->middleware('can:claim-review-campaign.filter-shipments');
Route::get('/download/{file}', 'DownloadController@download')->name('download-file');

Route::resource('claim-review-campaign', 'ClaimReviewCampaignController');

Route::resource('gift-card-template', 'GiftCardTemplateController');
Route::resource('leave-review-task', 'LeaveReviewTaskController');
Route::resource('managed-review-order', 'ManagedReviewOrderController');
Route::resource('owned-buyer-cart-item', 'OwnedBuyerCartItemController');
Route::resource('divvy-transaction-record', 'DivvyTransactionRecordController');
Route::resource('clicksend-history', 'ClickSendHistoryController');

Route::resource('customers', 'CustomerController', ['except' => ['show']]);

Route::resource('customers.customer-notes', 'CustomerNoteController');

Route::resource('owned-buyer', 'OwnedBuyerController', ['except' => ['show']]);
Route::get('/owned-buyer/{id}', 'OwnedBuyerController@show')->name('owned-buyer.show');

Route::resource('product-cost', 'ProductCostController', ['only' => ['store', 'update', 'destroy']]);
Route::resource('product-shipping-cost', 'ProductShippingCostController', ['only' => ['store', 'update', 'destroy']]);
Route::resource('product-fbm-shipping-cost', 'ProductFbmShippingCostController', ['only' => ['store', 'update', 'destroy']]);


Route::post('/claim-review-campaign/{id}/ajaxUpdate', 'ClaimReviewCampaignController@ajaxUpdate')->name('claim-review-campaign.ajaxUpdate')->middleware('can:claim-review-campaign.ajaxUpdate');
Route::put('/claim-review-campaign/{id}/send', 'ClaimReviewCampaignController@send')->name('claim-review-campaign.send')->middleware('can:claim-review-campaign.send');
Route::post('/claim-review-campaign/{id}/clicksendConfig', 'ClaimReviewCampaignController@createClicksendConfig')->name('claim-review-campaign.createClicksendConfig')->middleware('can:claim-review-campaign.createClicksendConfig');
Route::post('/claim-review-campaign/{id}/config', 'ClaimReviewCampaignController@createConfig')->name('claim-review-campaign.createConfig')->middleware('can:claim-review-campaign.createConfig');
Route::get('/claim-review-campaign/{id}/review-clicksend', 'ClaimReviewCampaignController@clicksendReview')->name('claim-review-campaign.review-clicksend')->middleware('can:claim-review-campaign.review-clicksend');
Route::get('/claim-review-campaign/{id}/review', 'ClaimReviewCampaignController@clicksendReview')->name('claim-review-campaign.review')->middleware('can:claim-review-campaign.review');
Route::put('/claim-review-campaign/{id}/send-via-api', 'ClaimReviewCampaignController@sendViaApi')->name('claim-review-campaign.send-via-api')->middleware('can:claim-review-campaign.send-via-api');

Route::post('/owned_buyer/import', 'OwnedBuyerController@import')->name('owned_buyer.import')->middleware('can:owned_buyer.import');
Route::get('/owned_buyer/find-eligible-buyers/{asin?}', 'OwnedBuyerController@findEligibleBuyers')->name('owned_buyer.find-eligible-buyers')->middleware('can:owned_buyer.find-eligible-buyers');

resources/views/customer/all.blade.php
@extends('layouts.master')
@section('title', "All Customers")
@section('content')
<ol class="breadcrumb">
  <li><a href="{{route('customers.dashboard')}}">Dashboard</a></li>
  @if (isset($country) && $country)
  <li><a href="{{route('customers.country-dashboard', ['country'=>$country])}}">{{$country}}</a></li>
  @endif
  <li class="active">All Customers</li>
</ol>
{!! $grid !!}
@endsection

resources/views/customer/country-dashboard.blade.php
@extends('layouts.master')
@section('title', "Customers")
@section('content')
<ol class="breadcrumb">
  <li><a href="{{route('customers.dashboard')}}">Dashboard</a></li>
  <li class="active">{{Locale::getDisplayRegion('-'.$country, 'us')}}</li>
</ol>

<div class="row">
  <div class="col-sm-3 col-xs-12">
    <div class="small-box bg-info">
      <div class="inner">
        <h3>{{number_format($customersCount)}}</h3>

        <p>Customers</p>
      </div>
      <a href="{{route('customers.all', ['country'=>$country])}}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <div class="col-sm-3 col-xs-12">
    <div class="small-box bg-success">
      <div class="inner">
        <h3>{{number_format($repeatBuyersCount)}}</h3>

        <p>Repeat Buyers</p>
      </div>
      <a href="{{route('customers.repeat-buyers', ['country'=>$country])}}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <div class="col-sm-3 col-xs-12">
    <div class="small-box bg-primary">
      <div class="inner">
        <h3>{{number_format($realEmailsCount) }}</h3>

        <p>Real Emails</p>
      </div>
      <a href="{{route('customers.real-email-buyers', ['country'=>$country])}}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <div class="col-sm-3 col-xs-12">
    <div class="small-box bg-brown">
      <div class="inner">
        <h3>{{number_format($positiveReviewersCount) }}</h3>

        <p>Positive Reviewers</p>
      </div>
      <a href="{{route('customers.positive-reviewer', ['country'=>$country])}}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-3 col-xs-12">
    <div class="small-box bg-orange">
      <div class="inner">
        <h3>{{number_format($negativeReviewersCount) }}</h3>

        <p>Negative Reviewers</p>
      </div>
      <a href="{{route('customers.negative-reviewer', ['country'=>$country])}}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div>
</div>
<hr>
<h4>Customers By State</h4>
<hr>
<table class="table table-strip">
  <thead>
    <tr>
      <th>State</th>
      <th>Customers</th>
    </tr>
  </thead>
  <tbody>
    @foreach ($stateCustomersCount as $stateCount)
      <tr>
        <td>{{ $stateCount->state }}</td>
        <td>{{ $stateCount->amount }}</td>
      </tr>
    @endforeach
  </tbody>
</table>

@endsection

resources/views/customer/dashboard.blade.php
@extends('layouts.master')
@section('title', "Customer Relationship Management")
@section('content')
  <div class="row country-grid">
  <?php $counter = 0; ?>
  @foreach ($customersCountByCountry as $country => $count)
    <div class="col-lg-2 col-md-3 col-sm-4 col-xs-12">
      <div class="small-box bg-background-{{$counter % 5}}">
        <div class="inner">
          <img src="{{asset('images/country-flags/' .strtolower($country). '.png')}}" alt="{{$country}}">
          <p>{{ Locale::getDisplayRegion('-'.$country, 'us') }}</p>
          <h3>{{number_format($count)}}</h3>
          <p>Customers</p>
        </div>
        <a href="{{route('customers.country-dashboard', ['country' => $country])}}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
      </div>
    </div>
    <?php $counter++; ?>
  @endforeach
  </div>
@endsection

resources/views/customer/real-email-buyers.blade.php
@extends('layouts.master')
@section('title', "Real Email Buyers")
@section('content')
<ol class="breadcrumb">
  <li><a href="{{route('customers.dashboard')}}">Dashboard</a></li>
  @if (isset($country) && $country)
  <li><a href="{{route('customers.country-dashboard', ['country'=>$country])}}">{{$country}}</a></li>
  @endif
  <li class="active">Real Email Buyers</li>
</ol>
{!! $grid !!}
@endsection

resources/views/customer/repeat-buyers.blade.php
@extends('layouts.master')
@section('title', "Repeat Buyers")
@section('content')
<ol class="breadcrumb">
  <li><a href="{{route('customers.dashboard')}}">Dashboard</a></li>
  @if (isset($country) && $country)
  <li><a href="{{route('customers.country-dashboard', ['country'=>$country])}}">{{$country}}</a></li>
  @endif
  <li class="active">Repeat Buyers</li>
</ol>
{!! $grid !!}
@endsection

resources/views/customer/show.blade.php
@extends('layouts.master')
@section('title', "Customer Detail ". $customer->name)
@section('content')
<ol class="breadcrumb">
  <li><a href="{{route('customers.dashboard')}}">Dashboard</a></li>
  <li class="active">{{$customer->name}}</li>
</ol>
<div class="panel panel-info">
  <div class="panel-heading">
    Profile
  </div>
  <div class="panel-body {{$customer->blocklisted ? 'blocklisted' : ''}}">
    <div class="row">
      <div class="col-xs-12 col-md-5">
        <table class="table table-striped">
          <tbody>
            <tr>
              <td>Blocklisted</td>
              <td>
                @can('edit-customer-info')
                  <input value="1" id="blocklisted"
                        data-size="small" 
                        data-pk="{{$customer->id}}"
                        data-method="PUT"
                        data-url="{{route('customers.update', ['id' => $customer->id])}}"
                        {{$customer->blocklisted ? 'checked' : ''}}
                        type="checkbox"
                        data-toggle="toggle">
                @endcan
              </td>
            </tr>
            <tr>
              <td>Name</td>
              <td>
                @can('edit-customer-info')
                <a href="#" class="editable" id="name" 
                    data-type="text" 
                    data-pk="{{$customer->id}}" 
                    data-url="{{route('customers.update', ['id' => $customer->id])}}" 
                    data-title="Customer Name">{{$customer->name}}</a>
                @else
                  {{$customer->name}}
                @endcan
                </td>
            </tr>
            <tr>
              <td>Real Email</td>
              <td>
              @can('edit-customer-info')
                <a href="#" class="editable" id="email" 
                    data-type="text" 
                    data-pk="{{$customer->id}}" 
                    data-url="{{route('customers.update', ['id' => $customer->id])}}" 
                    data-title="Customer Name">{{$customer->email}}</a>
              @else
                {{$customer->email}}
              @endcan
              </td>
            </tr>
            <tr>
              <td>Amazon Email</td>
              <td>{{$customer->amazon_buyer_email}}</td>
            </tr>
            <tr>
              <td>Facebook Account</td>
              <td>
              @can('edit-customer-info')
                <a href="#" class="editable" id="facebook_account" 
                    data-type="text" 
                    data-pk="{{$customer->id}}" 
                    data-url="{{route('customers.update', ['id' => $customer->id])}}" 
                    data-title="Customer Facebook">{{$customer->facebook_account}}</a>
              @else
                {{$customer->facebook_account}}
              @endcan
              </td>
            </tr>
            <tr>
              <td>Wechat Account</td>
              <td>
              @can('edit-customer-info')
                <a href="#" class="editable" id="wechat_account" 
                    data-type="text" 
                    data-pk="{{$customer->id}}" 
                    data-url="{{route('customers.update', ['id' => $customer->id])}}" 
                    data-title="Customer Wechat">{{$customer->wechat_account}}</a>
                @else
                  {{$customer->wechat_account}}
                @endcan
              </td>
            </tr>
            <tr>
              <td>Whatsapp Account</td>
              <td>
              @can('edit-customer-info')
                <a href="#" class="editable" id="whatsapp_account" 
                    data-type="text" 
                    data-pk="{{$customer->id}}" 
                    data-url="{{route('customers.update', ['id' => $customer->id])}}" 
                    data-title="Customer Whatapp">{{$customer->whatsapp_account}}</a>
              @else
                {{$customer->whatsapp_account}}
              @endcan
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="col-xs-12 col-md-4">
        <table class="table table-striped">
          @php
          if ($defaultShipment) {
            $address1 = $customer->address1 ?? $defaultShipment->ship_address_1;
            $address2 = $customer->address2 ?? $defaultShipment->ship_address_2;
          } else {
            $address1 = $customer->address1;
            $address2 = $customer->address2;
          }
          @endphp
          <tr>
            <td>Address1</td>
            <td>
            @can('edit-customer-info')
              <a href="#" class="editable" id="address1" 
                    data-type="text" 
                    data-pk="{{$customer->id}}" 
                    data-url="{{route('customers.update', ['id' => $customer->id])}}" 
                    data-title="Customer Address1">{{$address1}}
              </a>
              @else
                {{$customer->city}}
              @endcan
            </td>
          </tr>
          <tr>
            <td>Address2</td>
            <td>
            @can('edit-customer-info')
              <a href="#" class="editable" id="address2" 
                    data-type="text" 
                    data-pk="{{$customer->id}}" 
                    data-url="{{route('customers.update', ['id' => $customer->id])}}" 
                    data-title="Customer Address2">{{$address2}}
              </a>
              @else
                {{$customer->city}}
              @endcan
            </td>
          </tr>
          <tr>
            <td>City</td>
            <td>
            @can('edit-customer-info')
              <a href="#" class="editable" id="city" 
                    data-type="text" 
                    data-pk="{{$customer->id}}" 
                    data-url="{{route('customers.update', ['id' => $customer->id])}}" 
                    data-title="Customer City">{{$customer->city}}
              </a>
              @else
                {{$customer->city}}
              @endcan
            </td>
          </tr>
          <tr>
            <td>State</td>
            <td>
            @can('edit-customer-info')
              <a href="#" class="editable" id="state" 
                    data-type="text" 
                    data-pk="{{$customer->id}}" 
                    data-url="{{route('customers.update', ['id' => $customer->id])}}" 
                    data-title="Customer State">{{$customer->state}}</a>
                @else
                  {{$customer->state}}
                @endcan
            </td>
          </tr>
          <tr>
            <td>Country</td>
            <td>
              @can('edit-customer-info')
              <a href="#" class="editable" id="country" 
                    data-type="text" 
                    data-pk="{{$customer->id}}" 
                    data-url="{{route('customers.update', ['id' => $customer->id])}}" 
                    data-title="Customer Country">{{$customer->country}}</a>
              @else
                {{$customer->country}}
              @endcan
            </td>
          </tr>
          <tr>
            <td>Postal Code</td>
            <td>
            @can('edit-customer-info')
              <a href="#" class="editable" id="postal_code" 
                    data-type="text" 
                    data-pk="{{$customer->id}}" 
                    data-url="{{route('customers.update', ['id' => $customer->id])}}" 
                    data-title="Customer Name">{{$customer->postal_code}}</a>
            @else
              {{$customer->postal_code}}
            @endcan
            </td>
          </tr>
        </table>
      </div>
      <div class="col-xs-12 col-md-3">
        <table class="table table-striped">
          <tr>
            <td>Orders</td>
            <td>{{$customer->bought_orders_count}}</td>
          </tr>
          <tr>
            <td class="text-danger">Refunded Orders</td>
            <td class="text-danger">{{$customer->refunded_orders_count}}</td>
          </tr>
          <tr>
            <td>Postive Reviews</td>
            <td>{{$customer->leave_possitive_reviews_count}}</td>
          </tr>
          <tr>
            <td class="text-danger">Negative Reviews</td>
            <td class="text-danger">{{$customer->leave_negative_reviews_count}}</td>
          </tr>
          <tr>
            <td>Claim Reviews</td>
            <td>{{$customer->claim_reviews_count}}</td>
          </tr>
          <tr>
            <td>Invite Reviews</td>
            <td>{{$customer->invite_reviews_count}}</td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    Notes
  </div>
  <div class="panel-body">
    <ul>
    @foreach ($customer->customerNotes as $note)
      <li>
        <span>{{$userIdNameHash[$note->created_by]}}</span> Added At <time>{{$note->created_at}}</time> 
        <p>
        @can('edit-customer-info')
          <a href="#" class="editable" id="note" 
                data-type="textarea" 
                data-pk="{{$note->id}}" 
                data-url="{{route('customers.customer-notes.update', ['customer_id' => $customer->id, 'id' => $note->id])}}" 
                data-title="Customer Note">{{$note->note}}</a>
        @else
          {{$note->note}}
        @endcan
        </p>
      </li>
    @endforeach
    </ul>
    {{ Form::open(array('method'=>'post','url' => route('customers.customer-notes.store', ['customer_id' => $customer->id]), 'id'=>'new-note')) }}
      <input type="hidden" name="redirect" value="{{route('customers.show', ['id'=>$customer->id])}}">
      <div class="form-group">  
        <label for="note">Note:</label>
        <textarea required class="form-control" name="note" id="note" cols="15" rows="3"></textarea>
      </div>
      <button class="btn btn-primary">Add</button>
    {{ Form::close() }}
  </div>
</div>
<hr>
<section>
  <h3>Orders</h3>
  {!! $shipmentGrid !!}
  <hr>
</section>

<section>
  <h3>Claim Review Sent Out</h3>
  <table class="table table-strip">
    <thead>
      <tr>
        <th>Order Id</th>
        <th>Asin</th>
        <th>Campaign Name</th>
        <th>Supplier</th>
        <th>Gift Card Amount</th>
        <th>Campaign Created At</th>
        <th>Campaign Sent At</th>
        <th>Letter Design Front</th>
        <th>Letter Design Back</th>
        <th>Click Send Response</th>
        <th>Click Send Schedule Date</th>
      </tr>
    </thead>
    <tbody>
      @foreach ($orderItemMarketings as $oim)
        <tr>
          <td>{{ $oim->oim_amazon_order_id }}</td>
          <td>{{ $oim->asin }}</td>
          <td>{{ $oim->claimReviewCampaign->name }}</td>
          <td>{{ $oim->claimReviewCampaign->platform }}</td>
          <td>{{ $oim->claimReviewCampaign->cashback }}</td>
          <td>{{ $oim->created_at }}</td>
          <td>{{ $oim->sent_at }}</td>
          <td>
            @if ($oim->claimReviewCampaign->giftCardTemplate)
              <img class="small-thumbnail" src="{{$oim->claimReviewCampaign->giftCardTemplate->front_design_url}}" alt="">
            @endif
          </td>
          <td>
            @if ($oim->claimReviewCampaign->giftCardTemplate)
              <img class="small-thumbnail" src="{{$oim->claimReviewCampaign->giftCardTemplate->back_design_url}}" alt="">
            @endif
          </td>
          <th><pre>{{ $oim->click_send_response }}</pre></th>
          <th>{{ $oim->click_send_scheduled_send_at }}</th>
        </tr>
      @endforeach
    </tbody>
  </table>
  <hr>
</section>

<section>
<h3>Redeems</h3>
{!! $redeemGrid !!}
</section>

<script>
  $(document).ready(function() {
      $('.editable').editable({
        ajaxOptions: {
          type: 'put'
        },
        success: function () {console.log("Success Response from server")},
        error: function() {console.log("Error response form server")}
      });

      $('#blocklisted').on('change', function() {
        if (this.checked) {
          $(this).closest('.panel-body').addClass('blocklisted');
        } else {
          $(this).closest('.panel-body').removeClass('blocklisted');
        }
      });
  });
</script>
@endsection